# Generated by Django 6.0.2 on 2026-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['price'], 'verbose_name_plural': 'Store Products'},
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='source_url',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
